baseurl = "https://thesharpdev.com/"
languageCode = "en-us"
title = "The Sharp Dev"
copyright = "&copy; Copyright notice"
custom_css = "/static/css/custom.css"
theme = "hugo_theme_pickles"

[params]
  paginate = 10
  twitter = "wsharp07"
  github = "wsharp07"
  linkedin = "wsharp07"
  disqus = "thesharpdev"
  ga_api_key = "UA-106198224-1"
  author = "William Sharp"
  authorwebsite = "https://thesharpdev.com"
  avatar = "https://cdn.libravatar.org/avatar/1b312fa276ae1f589d8dd83c4368d31e"
  bio = "Staff Engineer at Rocket Companies"
  subtitle = "DevOps | Agile | Programming | Leadership"
  og_image = "/images/og_image.png"
  og_description = "Technology blog focused on Software Engineering, Leadership, DevOps, and Agile Software Development."
  #logo = "/path/to/logo"
  favicon = "/favicon.ico"
  custom_css = ["/css/custom.css"]

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = 2

[markup.goldmark.renderer]
  unsafe= true

[related]
  # Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
  threshold = 80

  # To get stable "See also" sections we, by default, exclude newer related pages.
  includeNewer = false

  # Will lower case keywords in both queries and in the indexes.
  toLower = false

  [[related.indices]]
  name = "keywords"
  weight = 150
  [[related.indices]]
  name  = "author"
  toLower = true
  weight = 30
  [[related.indices]]
  name  = "tags"
  weight = 100
  [[related.indices]]
  name  = "date"
  weight = 10
  pattern = "2017"
