name: 'End-to-end tests'
on:
  workflow_dispatch:
  pull_request:
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.6.0
        with:
          hugo-version: '0.98.0'

      - name: Setup Node 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci

      - name: Run Server
        run: npm run dev

      - name: Cypress run
        uses: cypress-io/github-action@v5.0.8
        with:
          browser: chrome
          headless: true
          record: false