name: End-to-end tests
on: [pull_request]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.6.0
        with:
          hugo-version: '0.98.0'

      - name: Run Server
        run: yarn dev

      - name: Cypress run
        uses: cypress-io/github-action@v5.0.8
        with:
          browser: chrome
          headless: true
          record: false