name: 'Tests'
on:
  workflow_dispatch:
  pull_request:
jobs:
  E2E:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.6.0
        with:
          hugo-version: '0.110.0'
          extended: true

      - name: Cypress run
        uses: cypress-io/github-action@v5.0.8
        with:
          start: npm run dev
          browser: chrome
          record: false