name: End-to-end tests
on: [pull_request]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.61.0'

      - name: Run Server
        run: ./run-dev.sh &

      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          start: npm run testci