name: End-to-end tests
on: [pull_request]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.61.0'

      - name: Run Server
        run: ./run-dev.sh
        with:
          parallel: true

      - name: Use Node.js 13.8.0
        uses: actions/setup-node@v1
        with:
          node-version: 13.8.0
      - run: npm install
      - run: npm run testci
        env:
          CI: true